config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_list.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.urls import path

from .views import (
    index,

    TasksListView,
    TaskCreateView,
    TaskUpdateView,
    UpdateTaskStatusView,
    TasklDeleteView,

    TagsListView,
    TagsCreateView,
    TagsUpdateView,
    TagsDeleteView,

)

urlpatterns = [
    path("", index, name="index"),

    path("tasks/", TasksListView.as_view(), name="tasks-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/update-status/", UpdateTaskStatusView.as_view(), name="update_task_status"),
    path("tasks/<int:pk>/delete/", TasklDeleteView.as_view(), name="task-delete"),

    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/create/", TagsCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagsUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagsDeleteView.as_view(), name="tags-delete"),
]

app_name = "todo_list"

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    deadline_datetime = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering=["-is_done", "created_datetime"]

    def __str__(self):
        return self.content[:50]

todo_list/forms.py
from django import forms
from todo_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        # fields = "__all__"
        fields = ['content', 'deadline_datetime', 'tags']

        widgets = {
            'deadline_datetime': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = "__all__"

todo_list/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from django.views.generic import FormView, CreateView
from django.urls import reverse_lazy

from todo_list.forms import TaskForm, TagForm
from todo_list.models import Task, Tag


@login_required
def index(request):
    num_tasks = Task.objects.count()
    num_task_in_progress = Task.objects.filter(is_done=False).count()

    context = {
        "num_tasks": num_tasks,
        "num_task_in_progress": num_task_in_progress,
    }

    return render(request, "todo_list/index.html", context=context)


class TasksListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 6
    context_object_name = "tasks_list"
    template_name = "todo_list/tasks_list.html"


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "todo_list/task_form.html"
    success_url = reverse_lazy("todo_list:tasks-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:tasks-list")


class UpdateTaskStatusView(View):
    def get(self, request, pk: int):
        task = get_object_or_404(Task, id=pk)
        task.is_done = not task.is_done
        task.save()

        return redirect("todo_list:tasks-list")


class TasklDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:tasks-list")


class TagsListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 5
    context_object_name = "tags_list"
    template_name = "todo_list/tags_list.html"


class TagsCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "todo_list/tags_form.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TagsUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = "todo_list/tags_form.html"
    success_url = reverse_lazy("todo_list:tags-list")


class TagsDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tags-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo_list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

</head>

<body>
{% load static %}
<div class="">
    <div class="row">
        {% if not user.is_authenticated %}
          {% block login %}{% endblock %}
          {% else %}
            <div class="col-sm-2">

                {% block sidebar %}
                    {% include "includes/sidebar.html" %}
                {% endblock %}

            </div>
            <div class="col-sm-10 ">

                {% block content %}
                {% endblock %}

                {% block pagination %}
                    {% include "includes/pagination.html" %}
                {% endblock %}
            </div>
        {% endif %}
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
  <div class="ml-3 mt-3 card mb-3 ">
    <a href="{% url 'logout' %}?next={{request.path}}" class="btn btn-secondary btn-block">Logout</a>
  </div>

  <ul class="list-group shadow-lg mt-6 ml-3">

    <li class="list-group-item">
      <a href="{% url 'todo_list:index' %}" class="btn btn-info btn-block">Home</a>
    </li>

    <li class="list-group-item">
      <a href="{% url 'todo_list:tasks-list' %}" class="btn btn-info btn-block">Tasks</a>
    </li>

    <li class="list-group-item">
      <a href="{% url 'todo_list:tags-list' %}" class="btn btn-info btn-block">All tags</a>
    </li>

  </ul>

templates/todo_list/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1 class="main-title text-lg-left">Tasks</h1>
    <p class="welcome-message">Welcome <strong>{{ user.get_username }}</strong></p>


      <div class="col-md-6">
        <div class="card shadow-lg mb-4">
          <div class="card-body">
            <h5 class="card-title text-primary">Total tasks</h5>
            <p class="card-text">{{ num_tasks }}</p>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card shadow-lg mb-4">
          <div class="card-body">
            <h5 class="card-title text-success">Task in progress</h5>
            <p class="card-text">{{ num_task_in_progress }}</p>
          </div>
        </div>
      </div>

      <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary bounceOut">Create new task</a>

  </div>
{% endblock %}

templates/todo_list/tags_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <input class="col-sm-4 control-label" type=button value="Cancel / Return" onClick="javascript:history.go(-1);">
  </form>
{% endblock %}

templates/todo_list/tags_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Submit" class="btn btn-primary">
    <input class="col-sm-4 control-label" type=button value="Cancel / Return" onClick="javascript:history.go(-1);">
  </form>
{% endblock %}

templates/todo_list/tags_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags List
    <a href="{% url 'todo_list:tags-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if tags_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tags_list %}
        <tr>

          <td>
              {{ tag.name }}
          </td>

          <td>
            <a style="color: #0040ff"
              href="{% url 'todo_list:tags-update' pk=tag.id %}">
              Update
            </a>
          </td>

          <td>
            <a style="color: red"
              href="{% url 'todo_list:tags-delete' pk=tag.id %}">
              Delete
            </a>
          </td>

        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags</p>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <input class="col-sm-4 control-label" type=button value="Cancel / Return" onClick="javascript:history.go(-1);">
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Submit" class="btn btn-primary">
    <input class="col-sm-4 control-label" type=button value="Cancel / Return" onClick="javascript:history.go(-1);">
  </form>
{% endblock %}

templates/todo_list/tasks_list.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h2 class="mt-4">
    Task list
    <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary">Create</a>
  </h2>

  {% if tasks_list %}
    <div class="row">
      <div class="col-md-6 ">
          <div class="card-header">
            <h4 class="card-title">Tasks in Progress</h4>
          </div>
          <div class="card-body">
            {% for task in tasks_list %}
              {% if not task.is_done %}
                <div class="card mb-3 shadow-lg">

                  <div class="order-header">
                    <strong><a>{{ task.content }}</a></strong>
                    <span class="badge text-primary">Tasks in Progress</span>
                  </div>

                    <p class="small">Task Creation Date: {{ task.created_datetime }}</p>
{#                  <p class="order-date">Task Deadline Date: {{ task.deadline_datetime }}</p>#}

                  <div>
                    <div class="order-actions">
                      <a href="{% url 'todo_list:task-update' task.id %}" class="btn btn-sm btn-info">Update</a>
                      <a href="{% url 'todo_list:task-delete' task.id %}" class="btn btn-sm btn-danger">Delete</a>
                  </div>

                    <sapn class="text-secondary">Tags:</sapn>
                      {% for tag in task.tags.all %}
                        <span class="badge">{{ tag.name }}</span>
                      {% endfor %}
                    <span class="float-right">
                    <a href="{% url 'todo_list:update_task_status' task.id %}" class="btn btn-sm btn-success">Complete</a>
                    </span>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
          <div class="card-header">
            <h2 class="card-title">Completed Tasks</h2>
          </div>
          <div class="card-body">
            {% for task in tasks_list %}
              {% if task.is_done %}
                <div class="card mb-3 shadow-lg">

                  <div class="order-header">
                    <strong><a>{{ task.content }}</a></strong>
                    <span class="badge text-warning">Task competed</span>
                  </div>

                    <p class="small">Task Deadline: {{ task.created_datetime }}</p>

                  <div class="order-actions">
                      <a href="{% url 'todo_list:task-update' task.id %}" class="btn btn-sm btn-info">Update</a>
                      <a href="{% url 'todo_list:task-delete' task.id %}" class="btn btn-sm btn-danger">Delete</a>
                  </div>

                  <div>
                    <sapn class="text-secondary">Tags:</sapn>
                      {% for tag in task.tags.all %}
                        <span class="badge">{{ tag.name }}</span>
                      {% endfor %}
                    <span class="float-right">
                    <a href="{% url 'todo_list:update_task_status' task.id %}" class="btn btn-sm btn-success">Undo</a>
                    </span>
                  </div>

                </div>
              {% endif %}
            {% endfor %}
          </div>
      </div>
    </div>
    </div>
  {% else %}
    <p class="no-orders-message">There are no tasks :(</p>
  {% endif %}
</div>

{% endblock %}